In [2]:
import pandas as pd
import numpy as np

In [3]:
ds=pd.Series([1,2,3,4,5],index=['v','h','a','b','s'],dtype='int',name='yash')
print(ds)

v    1
h    2
a    3
b    4
s    5
Name: yash, dtype: int32

In [4]:
ds=pd.Series((1,2,3,4,5),index=['v','h','a','b','s'],dtype='int',name='yash')
print(ds)

v    1
h    2
a    3
b    4
s    5
Name: yash, dtype: int32

In [5]:
ds=pd.Series({"name":"yash","age":"21"},dtype='int')
print(ds)

ValueError: invalid literal for int() with base 10: 'yash'

In [ ]:
a=np.array([1,2,3,4])
ds=pd.Series(a,index=['v','h','a','b'],dtype='int',name='yash')
print(ds)

In [ ]:
ds=pd.DataFrame([['a','b','c','d'],[1,2,3],[5,6,7]],index=['p','q','r'],columns=['y','a','s','h'])
print(ds)

In [ ]:
ds=pd.DataFrame((('a','b','c','d'),(1,2,3),(5,6,7)),index=['p','q','r'],columns=['y','a','s','h'])
print(ds)

In [ ]:
ds=pd.DataFrame({'name':['y','a','s','h'],'mark':[10,20,30,40],index=['p','q','r','a'])
print(ds)

In [6]:
print(ds.name)

yash

In [7]:
ds=pd.read_csv('train.csv')

In [8]:
print(ds)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [9]:
ds.index

RangeIndex(start=0, stop=891, step=1)

In [10]:
ds.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
ds.size

10692

In [12]:
ds.shape

(891, 12)

In [13]:
ds.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [14]:
ds.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [15]:
ds.ndim

2

In [16]:
ds.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22,38,26,35,35,NaN,54,2,27,14,...,33,22,28,25,39,27,19,NaN,26,32
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13,30,23.45,30,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

In [29]:
ds.T

Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Thayer)","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22,38,26,35,35,NaN,54,2,27,14,...,33,22,28,25,39,27,19,NaN,26,32
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13,30,23.45,30,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

In [33]:
ds=ds.set_index('Name')

KeyError: "None of ['Name'] are in the columns"

In [34]:
ds.reset_index()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [28]:
print(ds)

                                                    PassengerId  Survived  \
Name
Braund, Mr. Owen Harris                                       1         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Allen, Mr. William Henry                                      5         0
...                                                         ...       ...
Montvila, Rev. Juozas                                       887         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0
Behr, Mr. Karl Howell                                       890         1
Dooley, Mr. Patrick                                         891         0

                                                    Pclass     Sex   Age  \
Name
Braund, Mr. Owen Harris                                  3    male  22.0
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Allen, Mr. William Henry                                 3    male  35.0
...                                                    ...     ...   ...
Montvila, Rev. Juozas                                    2    male  27.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN
Behr, Mr. Karl Howell                                    1    male  26.0
Dooley, Mr. Patrick                                      3    male  32.0

                                                    SibSp  Parch  \
Name
Braund, Mr. Owen Harris                                 1      0
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Allen, Mr. William Henry                                0      0
...                                                   ...    ...
Montvila, Rev. Juozas                                   0      0
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2
Behr, Mr. Karl Howell                                   0      0
Dooley, Mr. Patrick                                     0      0

                                                              Ticket     Fare  \
Name
Braund, Mr. Owen Harris                                    A/5 21171   7.2500
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Allen, Mr. William Henry                                      373450   8.0500
...                                                              ...      ...
Montvila, Rev. Juozas                                         211536  13.0000
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500
Behr, Mr. Karl Howell                                         111369  30.0000
Dooley, Mr. Patrick                                           370376   7.7500

                                                   Cabin Embarked
Name
Braund, Mr. Owen Harris                              NaN        S
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C
Heikkinen, Miss. Laina                               NaN        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S
Allen, Mr. William Henry                             NaN        S
...                                                  ...      ...
Montvila, Rev. Juozas                                NaN        S
Graham, Miss. Margaret Edith                         B42        S
Johnston, Miss. Catherine Helen "Carrie"             NaN        S
Behr, Mr. Karl Howell                               C148        C
Dooley, Mr. Patrick                                  NaN        Q

[891 rows x 11 columns]

In [31]:
temp=pd.read_csv('train.csv')

In [61]:
df1=pd.DataFrame({'name':['a','b','c'],'marks':[1,2,3],'cgpa':[1,2,3]})

In [57]:
df1=df1.set_index("name",drop=False)

In [62]:
df1=df1.set_index("name")
print(df1)

      marks  cgpa
name
a         1     1
b         2     2
c         3     3

In [63]:
df1=df1.reset_index()

In [64]:
print(df1)

  name  marks  cgpa
0    a      1     1
1    b      2     2
2    c      3     3

In [110]:
df=pd.read_csv('train.csv')

In [83]:
type(df['Name'])

pandas.core.series.Series

In [84]:
a=pd.DataFrame(df['Name'],df['Pclass'])

In [85]:
print(a)

                                                     Name
Pclass
3            Futrelle, Mrs. Jacques Heath (Lily May Peel)
1       Cumings, Mrs. John Bradley (Florence Briggs Th...
3            Futrelle, Mrs. Jacques Heath (Lily May Peel)
1       Cumings, Mrs. John Bradley (Florence Briggs Th...
3            Futrelle, Mrs. Jacques Heath (Lily May Peel)
...                                                   ...
2                                  Heikkinen, Miss. Laina
1       Cumings, Mrs. John Bradley (Florence Briggs Th...
3            Futrelle, Mrs. Jacques Heath (Lily May Peel)
1       Cumings, Mrs. John Bradley (Florence Briggs Th...
3            Futrelle, Mrs. Jacques Heath (Lily May Peel)

[891 rows x 1 columns]

In [86]:
type(df[['Name','Pclass']])

pandas.core.frame.DataFrame

In [87]:
df[['Name','Pclass']]

                                                  Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
888           Johnston, Miss. Catherine Helen "Carrie"       3
889                              Behr, Mr. Karl Howell       1
890                                Dooley, Mr. Patrick       3

[891 rows x 2 columns]

In [88]:
df.iloc[2]

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                                26
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [89]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [90]:
df.iloc[2,3]

'Heikkinen, Miss. Laina'

In [91]:
df.iloc[1:10,2:5]

   Pclass                                               Name     Sex
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2       3                             Heikkinen, Miss. Laina  female
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4       3                           Allen, Mr. William Henry    male
5       3                                   Moran, Mr. James    male
6       1                            McCarthy, Mr. Timothy J    male
7       3                     Palsson, Master. Gosta Leonard    male
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9       2                Nasser, Mrs. Nicholas (Adele Achem)  female

In [94]:
df.iloc[:,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [111]:
df=df.set_index('Name')

In [97]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [113]:
df.loc["Braund, Mr. Owen Harris":"Montvila, Rev. Juozas"]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Dahlberg, Miss. Gerda Ulrika",883,0,3,female,22.0,0,0,7552,10.5167,NaN,S
"Banfield, Mr. Frederick James",884,0,2,male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
"Sutehall, Mr. Henry Jr",885,0,3,male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
"Rice, Mrs. William (Margaret Norton)",886,0,3,female,39.0,0,5,382652,29.1250,NaN,Q
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S

In [116]:
df1=pd.DataFrame({'P':[10,20,30],'Q':[40,50,60],'R':[70,80,90]},index=['A',"B",'C'])

In [132]:
df1

    P    Q   R
A  10   40  70
B  20  100  80
C  30   60  90

In [120]:
df1.iloc[1,1]

50

In [131]:
df1.loc['B',"Q"]=100

In [123]:
df1.loc['B']

P    20
Q    50
R    80
Name: B, dtype: int64

In [130]:
df1.loc[['A','B','C'],'R']

A    70
B    80
C    90
Name: R, dtype: int64

In [134]:
df1['D']=7

In [135]:
df1

    P    Q   R  D
A  10   40  70  7
B  20  100  80  7
C  30   60  90  7

In [137]:
df1['D']=[1,2,3]

In [138]:
df1

    P    Q   R  D
A  10   40  70  1
B  20  100  80  2
C  30   60  90  3