In [85]:
import pandas as pd
import numpy as np

In [105]:
df=pd.DataFrame(np.random.randint(1,100,(10,4)),columns=['A','B','C','D'])

In [99]:
df

    A   B   C   D
0   2  29  50  18
1  39  34  39  89
2  54  72  55  80
3  95  56  99  27
4  34   8  93  79
5  42  39  97   6
6  78  92  27   1
7  67   4  77  85
8   6  10  11  59
9  93  11  15  46

In [100]:
df.apply(sum,axis=0)

A    510
B    355
C    563
D    490
dtype: int64

In [89]:
df["Total"]=df.apply(sum,axis=1)

In [90]:
df

    A   B   C   D  Total
0  67  59   4  29    159
1   1  99  43  11    154
2  75  91  66  78    310
3   2  60  67  40    169
4  97  29  56  60    242
5  27   4  80  89    200
6  81  79  81  99    340
7  31  56  85  90    262
8   7  45  38  99    189
9  78  32  27  66    203

In [91]:
df.apply(lambda x:(x['A']+x['B']+x['C'])/3,axis=1)

0    43.333333
1    47.666667
2    77.333333
3    43.000000
4    60.666667
5    37.000000
6    80.333333
7    57.333333
8    30.000000
9    45.666667
dtype: float64

In [92]:
df["result"]=df.apply(lambda x:'Fail' if ((x["A"]<35) or (x["B"]<35) or (x["C"]<35) or (x["D"]<35)) else "Pass",axis=1)

In [93]:
df

    A   B   C   D  Total result
0  67  59   4  29    159   Fail
1   1  99  43  11    154   Fail
2  75  91  66  78    310   Pass
3   2  60  67  40    169   Fail
4  97  29  56  60    242   Fail
5  27   4  80  89    200   Fail
6  81  79  81  99    340   Pass
7  31  56  85  90    262   Fail
8   7  45  38  99    189   Fail
9  78  32  27  66    203   Fail

200> a+
180 a
170 b
150 c
f

In [94]:
def grade(total):
    if(total>200):
        return "A+"
    elif(total>180):
        return "A"
    elif(total>170):
        return "B"
    elif(total>150):
        return "C"
    else:
        return "F"

In [95]:
df["Grade"]=df["Total"].apply(grade)

In [96]:
df

    A   B   C   D  Total result Grade
0  67  59   4  29    159   Fail     C
1   1  99  43  11    154   Fail     C
2  75  91  66  78    310   Pass    A+
3   2  60  67  40    169   Fail     C
4  97  29  56  60    242   Fail    A+
5  27   4  80  89    200   Fail     A
6  81  79  81  99    340   Pass    A+
7  31  56  85  90    262   Fail    A+
8   7  45  38  99    189   Fail     A
9  78  32  27  66    203   Fail    A+

In [106]:
df[["r","x"]]=df.apply([sum,max],axis=1)

In [107]:
df

    A   B   C   D    r   x
0  78  98  82  41  299  98
1  61  85  45  10  201  85
2   4  84  28  62  178  84
3  82  98  45  83  308  98
4  96   3   1  47  147  96
5  65  22  94  24  205  94
6  91  95  16  78  280  95
7  74   9  92  74  249  92
8  11  49   3  29   92  49
9  57  19  11  24  111  57